# This file is machine-generated - editing it directly is not advised

[[BinaryProvider]]
deps = ["Libdl", "SHA"]
git-tree-sha1 = "5b08ed6036d9d3f0ee6369410b830f8873d4024c"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.8"

[[CxxWrap]]
deps = ["BinaryProvider", "Libdl"]
git-tree-sha1 = "c7865f82d1ccfd98d11bba256bd22c27b5ca2864"
uuid = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
version = "0.8.2"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
