name = "Z3"
uuid = "06b161dc-0161-11ea-0f74-41f836f4024b"
authors = ["Andreas Humenberger <ahumenberger@gmail.com>"]
version = "0.4.2"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
z3_jll = "1bc4e1ec-7839-5212-8f2f-0d16b7bd09bc"

[compat]
CxxWrap = "0.12.0"
julia = "1.6"
z3_jll = "4.8.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
