name = "Z3"
uuid = "06b161dc-0161-11ea-0f74-41f836f4024b"
authors = ["Andreas Humenberger <ahumenberger@gmail.com>"]
version = "0.3.0"

[deps]
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
CMake = "1.1.2"
CxxWrap = "0.8.2"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]